---
title: "Combat FS"
author: "TM, MA"
date: "06/16/2025; 07/15/2025; 10/1/25; 12/10/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#don't have tidyverse loaded
library(longCombat)
unloadNamespace("tidyverse")
```

## Load and organize the data
```{r}
#load RDS file generated from the IPTW scripts. 
data <- readRDS("/Volumes/groups/Neurosurgery Research -Clinical/Meier, Tim/Active Projects/CARE-CMV/Analyses/2ndBatchCMV/DataAnalysis/MRI/121025/data_MRI_PIRPT.rds")

#Data already restricted to visits of interest and those without CMV removed. 

# Convert variables to appropriate types
data$Race_recode <- factor(data$Race_recode)
data$Ethnicity_recode <- factor(data$Ethnicity_recode)
data$MILACADEMY <- factor(data$MILACADEMY)
data$SEX <- factor(data$SEX)
data$mTBIvsCtrl <- factor(data$mTBIvsCtrl)
data$SPORTSRC <- factor(data$SPORTSRC)
data$COMBATSRC <- factor(data$COMBATSRC)
data$MILCADET <- factor(data$MILCADET)
data$mTBI_CMV_Comb <- factor(data$mTBI_CMV_Comb)
data$mTBI_CMV_PI <- factor(data$mTBI_CMV_PI)
data$SRC_CMV_comb <- factor(data$SRC_CMV_comb)
data$SRC_CMV_PI <- factor(data$SRC_CMV_PI)
data$CMV_STATUS_COMBINE <- factor(data$CMV_STATUS_COMBINE)
data$INJURYID <- as.factor(data$INJURYID)
data$ScanSite <- as.factor(data$ScanSite)
data$ScanCoilSite <- factor(data$ScanCoilSite)
data$RSFC_QA <- factor(data$RSFC_QA)
data$RSFC_QA_final <- factor(data$RSFC_QA_final)
data$FD_mean_group <- factor(data$FD_mean_group)
data$FS_QA <- factor(data$FS_QA)
data$AUTOPTX_exclude <- factor(data$AUTOPTX_exclude)

# Recode CMV_STATUS to binary treatment variable using  CMV_PI
# CMV+ = 1 (treated), CMV- = 0 (control)
data$CMV_BINARY <- data$CMV_PI
data$CMV_BINARY <- factor(data$CMV_BINARY, levels=c("0", "1"), labels=c("CMV-", "CMV+"))

#Select the ROI - harmonizing across all of them. 
roi <- c("lh_MeanThickness_thickness", 
                  "lh_bankssts_thickness", 
                  "lh_caudalanteriorcingulate_thickness", 
                  "lh_caudalmiddlefrontal_thickness", 
                  "lh_cuneus_thickness", 
                  "lh_entorhinal_thickness", 
                  "lh_fusiform_thickness", 
                  "lh_inferiorparietal_thickness", 
                  "lh_inferiortemporal_thickness", 
                  "lh_isthmuscingulate_thickness", 
                  "lh_lateraloccipital_thickness", 
                  "lh_lateralorbitofrontal_thickness", 
                  "lh_lingual_thickness", 
                  "lh_medialorbitofrontal_thickness", 
                  "lh_middletemporal_thickness", 
                  "lh_parahippocampal_thickness", 
                  "lh_paracentral_thickness", 
                  "lh_parsopercularis_thickness", 
                  "lh_parsorbitalis_thickness", 
                  "lh_parstriangularis_thickness", 
                  "lh_pericalcarine_thickness", 
                  "lh_postcentral_thickness", 
                  "lh_posteriorcingulate_thickness", 
                  "lh_precentral_thickness", 
                  "lh_precuneus_thickness", 
                  "lh_rostralanteriorcingulate_thickness", 
                  "lh_rostralmiddlefrontal_thickness", 
                  "lh_superiorfrontal_thickness", 
                  "lh_superiorparietal_thickness", 
                  "lh_superiortemporal_thickness", 
                  "lh_supramarginal_thickness", 
                  "lh_frontalpole_thickness", 
                  "lh_temporalpole_thickness", 
                  "lh_transversetemporal_thickness", 
                  "lh_insula_thickness",
                  "rh_MeanThickness_thickness", 
                  "rh_bankssts_thickness", 
                  "rh_caudalanteriorcingulate_thickness", 
                  "rh_caudalmiddlefrontal_thickness", 
                  "rh_cuneus_thickness", 
                  "rh_entorhinal_thickness", 
                  "rh_fusiform_thickness", 
                  "rh_inferiorparietal_thickness", 
                  "rh_inferiortemporal_thickness", 
                  "rh_isthmuscingulate_thickness", 
                  "rh_lateraloccipital_thickness", 
                  "rh_lateralorbitofrontal_thickness", 
                  "rh_lingual_thickness", 
                  "rh_medialorbitofrontal_thickness", 
                  "rh_middletemporal_thickness", 
                  "rh_parahippocampal_thickness", 
                  "rh_paracentral_thickness", 
                  "rh_parsopercularis_thickness", 
                  "rh_parsorbitalis_thickness", 
                  "rh_parstriangularis_thickness", 
                  "rh_pericalcarine_thickness", 
                  "rh_postcentral_thickness", 
                  "rh_posteriorcingulate_thickness", 
                  "rh_precentral_thickness", 
                  "rh_precuneus_thickness", 
                  "rh_rostralanteriorcingulate_thickness", 
                  "rh_rostralmiddlefrontal_thickness", 
                  "rh_superiorfrontal_thickness", 
                  "rh_superiorparietal_thickness", 
                  "rh_superiortemporal_thickness", 
                  "rh_supramarginal_thickness", 
                  "rh_frontalpole_thickness", 
                  "rh_temporalpole_thickness", 
                  "rh_transversetemporal_thickness", 
                  "rh_insula_thickness")

###Subset the analysis to include only subjects with GOOD data
fs_data<- subset(data, rh_MeanThickness_thickness > 0)
fs_data1<- subset(fs_data, FS_QA != "Unusable FS")

fs_data2 <- fs_data1[c("INJURYID", 
                   "mTBI_CMV_PI", 
                   "VISIT",
                   "iptw", 
                   "ScanSite",
                   roi)]


```

## Run ComBat
```{r}
# basic model
combat <- longCombat(idvar='INJURYID', 
             timevar = "VISIT",
             batchvar='ScanSite', 
             features= roi,
             formula="mTBI_CMV_PI*VISIT",
             ranef='(1|INJURYID)',
             data=fs_data2)

fs_data_combat <- combat$data_combat

#merge with original data - using 'fs_data1' since that has the bad data removed already. 
data_all <- merge(fs_data1, fs_data_combat, by=c('INJURYID', 'VISIT'))

#Save R file (should keep all structure and labels)
saveRDS(data_all, "/Volumes/groups/Neurosurgery Research -Clinical/Meier, Tim/Active Projects/CARE-CMV/Analyses/2ndBatchCMV/DataAnalysis/MRI/121025/Rdata/data_MRI_PIRPT_FScombat.rds")

```

## Correlate output

```{r}

# CREATE VECTOR FOR COMBAT VARIABLES
roi_combat <- names(data_all)[grepl("\\.combat$", names(data_all))]

# COMPUTE PAIRED CORRELATIONS ACROSS VISITS
corr_df <- data.frame(
  variable = roi,
  sapply(c("24H", "Asymp", "PRTP", "6Mo"), function(v) {
    sapply(seq_along(roi), function(i) {
      x <- data_all[[roi[i]]][data_all$VISIT == v]
      y <- data_all[[roi_combat[i]]][data_all$VISIT == v]
      valid <- !is.na(x) & !is.na(y)
      corr <- cor(x[valid], y[valid], use = "complete.obs")
      n <- sum(valid)
      paste0(round(corr, 3), " (n = ", n, ")")})}),
  stringsAsFactors = FALSE)

corr_df

```

# Plots
```{r}
# batch boxplots
batchBoxplot(idvar='INJURYID', 
             batchvar='ScanSite.x', 
             feature='lh_MeanThickness_thickness',
             formula='mTBI_CMV_PI*VISIT',
             ranef='(1|INJURYID)',
             adjustBatch = FALSE,
             data=data_all)
batchBoxplot(idvar='INJURYID', 
             batchvar='ScanSite.x', 
             feature='lh_MeanThickness_thickness.combat',
             formula='mTBI_CMV_PI*VISIT',
             ranef='(1|INJURYID)',
             adjustBatch = FALSE,
             data=data_all)

# mean boxplots
boxplot(data_all$lh_MeanThickness_thickness ~ data_all$ScanSite.x, 
        main = "PRE: lh_MeanThickness_thickness by ScanSite",
        xlab = "ScanSite.x", 
        ylab = "lh_MeanThickness_thickness")

boxplot(data_all$lh_MeanThickness_thickness.combat ~ data_all$ScanSite.x, 
        main = "POST: lh_MeanThickness_thickness by ScanSite",
        xlab = "ScanSite.x", 
        ylab = "lh_MeanThickness_thickness")


#check all PRE combated ROIs

addTest(idvar='INJURYID',
        batchvar='ScanSite.x',
        features=roi,
        formula='mTBI_CMV_PI*VISIT',
        ranef='(1|INJURYID)',
        data=data_all)
multTest(idvar='INJURYID',
         batchvar='ScanSite.x',
         features=roi,
         formula='mTBI_CMV_PI*VISIT',
         ranef='(1|INJURYID)',
         data=data_all)

#check all POST combated ROIs
addTest(idvar='INJURYID',
        batchvar='ScanSite.x',
        features=roi_combat,
        formula='mTBI_CMV_PI*VISIT',
        ranef='(1|INJURYID)',
        data=data_all)
multTest(idvar='INJURYID',
         batchvar='ScanSite.x',
         features=roi_combat,
         formula='mTBI_CMV_PI*VISIT',
         ranef='(1|INJURYID)',
         data=data_all)

```
